Solved the LaTeX2exp error. Closes #2027
plotly/plotly.R pull request #2030
Opened 2021-09-28 08:06 UTC by moutikabdessabour

Solved The LaTeX2exp error. for more information check #2027.

Same code now gives the correct output.
```r
library(plotly)
library(latex2exp)
library(ggplot2)

p <- qplot(1, "A")+
     ylab(TeX("Formula: $\\frac{2hc^2}{\\lambda^\\beta}$"))+
     xlab(TeX("$\\alpha$"))

ggplotly(p)
```

![](https://user-images.githubusercontent.com/11250014/135048116-7b000749-d720-48e1-94eb-702f267488ac.png)

2021-09-28 15:14 UTC, moutikabdessabour commented
`RCMD check` still gives warning even though I do not export the modified `uniq` function. 😞

2021-09-28 15:41 UTC, jackparmer commented
Awesome. Yes please add _snaps folder to .gitignore in a separate PR

2021-09-28 17:04 UTC, cpsievert requested changes
Please revert the `export(uniq)` and whitespace changes

Also, the `_snaps` folder should be checked into git, not ignored

2021-09-28 21:38 UTC, moutikabdessabour commented
@cpsievert the whitespace changes are caused by my R linter, sorry for that.

2021-10-08 16:58 UTC, cpsievert commented
@moutikabdessabour please revert the removal of the visual tests and add a test demonstrating the fix

2021-10-09 11:52 UTC, moutikabdessabour commented
@cpsievert done

2021-11-01 17:29 UTC, cpsievert commented on tests/testthat/helper-vdiffr.R
> +  writeLines(svg_txt, basename(file))
What is `write_plotly_csv`?

2021-11-01 17:34 UTC, merged